CREATE USER webl2 IDENTIFIED BY webl2;

CREATE TABLESPACE tb_webl2
    DATAFILE 'C:/oracle/oradata/tests/dat_webl2.dbf'
    SIZE 10M AUTOEXTEND ON;

GRANT RESOURCE, CONNECT, CTXAPP, DBA TO webl2;

GRANT EXECUTE ON CTXSYS.CTX_DDL TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_CLS TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_DOC TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_THES TO webl2;
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO webl2;

GRANT CREATE ANY DIRECTORY TO webl2;

ALTER USER webl2 DEFAULT TABLESPACE tb_webl2;